name: Build and Deploy Cuvio Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build with Eleventy
        run: npx @11ty/eleventy
        
      - name: Generate sitemap
        run: |
          # Generate sitemap.xml
          echo '<?xml version="1.0" encoding="UTF-8"?>' > _site/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> _site/sitemap.xml
          echo '  <url>' >> _site/sitemap.xml
          echo '    <loc>https://cuvio.co.uk/</loc>' >> _site/sitemap.xml
          echo '    <lastmod>'$(date -u +%Y-%m-%d)'</lastmod>' >> _site/sitemap.xml
          echo '    <changefreq>weekly</changefreq>' >> _site/sitemap.xml
          echo '    <priority>1.0</priority>' >> _site/sitemap.xml
          echo '  </url>' >> _site/sitemap.xml
          echo '  <url>' >> _site/sitemap.xml
          echo '    <loc>https://cuvio.co.uk/recipes/</loc>' >> _site/sitemap.xml
          echo '    <lastmod>'$(date -u +%Y-%m-%d)'</lastmod>' >> _site/sitemap.xml
          echo '    <changefreq>monthly</changefreq>' >> _site/sitemap.xml
          echo '    <priority>0.8</priority>' >> _site/sitemap.xml
          echo '  </url>' >> _site/sitemap.xml
          echo '</urlset>' >> _site/sitemap.xml
          
      - name: Generate robots.txt
        run: |
          echo 'User-agent: *' > _site/robots.txt
          echo 'Allow: /' >> _site/robots.txt
          echo 'Sitemap: https://cuvio.co.uk/sitemap.xml' >> _site/robots.txt
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4